In [1]:
%load_ext autoreload
%autoreload 2

# Loading Data

In [2]:
import sys
import os

sys.path.append(os.path.abspath(os.path.join('..')))

from src.data.loader import load_raw_data

#Load the data into a DataFrame variable
df_not_clean = load_raw_data()

print(f"Data shape: {df_not_clean.shape}")

Successfully located and loaded raw data from: data/raw/agent_tool_tasks.csv
Data shape: (3491, 33)

# Adding features

### Adding Mandatory Features

In [3]:
import pandas as pd
import sys

sys.path.append('../')
import src.features.mandatory as mandatory

df = mandatory.fill_missing_text(df_not_clean)

df_Mfeatures = mandatory.build_mandatory_features(df)

columns_to_check = [
    'query', 'query_avg_word_length', 
    'tool_names', 'tool_name_diversity', 
    'avg_params_per_tool','required_params_ratio',
    'query_mentions_number'
]
display(df_Mfeatures[columns_to_check].head())
print(f"Data shape: {df_Mfeatures.shape}")

,query,query_avg_word_length,tool_names,tool_name_diversity,avg_params_per_tool,required_params_ratio,query_mentions_number
0,air,3.000000,ThinQ_Connect,1,1.0,1.00,0
1,what is your name?,3.750000,get_current_weather,1,2.0,0.50,0
2,Could you give me Python code that get 2 int t...,3.933333,get_current_weather,1,2.0,0.50,1
3,Find me the most recent art sculpture by James...,5.230769,get_zodiac_compatibility|local_nursery.find|ge...,4,2.5,0.70,0
4,"""Can you help me find a recipe that uses chick...",4.816667,restaurant.find|recipe.find,2,2.0,0.75,1

Data shape: (3491, 38)

### Adding Custom Features

In [4]:
sys.path.append('../')
from src.features.custom import build_custom_features

# Apply the custom features
df_features = build_custom_features(df_Mfeatures)

# Verify
columns_to_check = [
    'query', 'comparison_keywords','example_keywords','total_relations', 
    'relation_words_ratio', 'is_generative_query'
]
display(df_features[columns_to_check].head(5))
print(f"Data shape: {df_features.shape}")

,query,comparison_keywords,example_keywords,total_relations,relation_words_ratio,is_generative_query
0,air,0,0,0,0.000000,0
1,what is your name?,0,0,0,0.000000,0
2,Could you give me Python code that get 2 int t...,0,0,1,0.071429,0
3,Find me the most recent art sculpture by James...,0,0,0,0.000000,0
4,"""Can you help me find a recipe that uses chick...",1,0,8,0.137931,0

Data shape: (3491, 43)

# Cleaning and Transformation

### Filling missing values

In [5]:
from src.pipelines.preprocessing import missing_value_imputation
df_train, df_val, df_test = missing_value_imputation(df_features)
print(f"Train shape: {df_train.shape}")
print(f"Validation shape: {df_val.shape}")
print(f"Test shape: {df_test.shape}")

Train shape: (2792, 43)
Validation shape: (349, 43)
Test shape: (350, 43)

### Transformation

In [6]:
sys.path.append('../')
from src.pipelines.preprocessing import preprocess_data

X_train_processed, X_val_processed, X_test_processed, y_train, y_val, y_test = preprocess_data(df_features)
print(f"Preprocessing Complete!")
print(f"Train matrix shape: {X_train_processed.shape}")
print(f"Validation matrix shape: {X_val_processed.shape}")
print(f"Test matrix shape: {X_test_processed.shape}")

Preprocessing Complete!
Train matrix shape: (2792, 48)
Validation matrix shape: (349, 48)
Test matrix shape: (350, 48)